- id: add-dco
  name: 'Add DCO sign-off'
  entry: hooks/add-dco
  description: adds DCO sign off into commit
  language: script
  files: .*
  stages: [commit-msg]
- id: gradle-spotless
  name: 'Gradle Java Spotless'
  entry: hooks/gradle-spotless
  description: runs gradle spotless for java in the current project
  language: script
  files: .*
  stages: [pre-commit]
